name: Generate Snake  
on:  
  schedule:  
    - cron: "0 0 * * *"  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Generate Snake Animation  
        uses: Platane/snk@master  
        with:  
          github_user_name: joao-barbosa-py  
          outputs: dist/snake.svg  

      - name: Push to the output branch  
        uses: crazy-max/ghaction-github-pages@v2  
        with:  
          target_branch: output  
          build_dir: dist  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
