name: Generate Snake  
on:  
  schedule:  
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC  
  workflow_dispatch:  # Permite rodar manualmente  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Baixar código-fonte  
        uses: actions/checkout@v3  

      - name: Gerar animação Snake  
        uses: Platane/snk/svg-only@v3  
        with:  
          github_user_name: SEU_USUARIO  
          outputs: snake.svg  

      - name: Publicar no branch output  
        uses: crazy-max/ghaction-github-pages@v2  
        with:  
          target_branch: output  
          build_dir: .  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

