name: Generate Snake  
on:  
  schedule:  
    - cron: "0 0 * * *"  
  workflow_dispatch: 

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Baixar código-fonte
        uses: actions/checkout@v3  

      - name: Gerar animação Snake
        uses: Platane/snk@v3  # Usa a versão mais recente do repositório
        with:  
          github_user_name: joao-barbosa-py
          svg_out_path: dist/snake.svg  # Caminho correto para salvar a animação

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v2  
        with:  
          target_branch: output  
          build_dir: dist 
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
