name: Generate Snake  
on:  
  schedule:  
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC  
  workflow_dispatch:  # Permite rodar manualmente  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Baixar código-fonte  
        uses: actions/checkout@v3  

      - name: Criar diretório de saída  
        run: mkdir -p dist  

      - name: Gerar animação Snake  
        uses: Platane/snk@master  
        with:  
          github_user_name: joao-barbosa-py
          svg_out_path: dist/snake.svg  
      - name: Publicar no branch output  
        uses: JamesIves/github-pages-deploy-action@v4  
        with:  
          branch: output  
          folder: dist  
